language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install: npm install
before_script: echo 'No unit test coverage for Booklists; Will attempt to build distribution
  assets as a safety'
script: npm run dist
before_deploy: echo 'Successfully built distribution assets for Booklists; Preparing
  to deploy New Arrivals to AWS'
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: nypl-booklists
  env: nypl-booklists-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: nypl-booklists-production
  on:
    repo: NYPL/dgx-booklists
    branch: master
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  region: us-east-1
  app: nypl-booklists
  env: nypl-booklists-qa
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: nypl-booklists-qa
  on:
    repo: NYPL/dgx-booklists
    branch: qa
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  region: us-east-1
  app: nypl-booklists
  env: nypl-booklists-development
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: nypl-booklists-development
  on:
    repo: NYPL/dgx-booklists
    branch: development
    condition: false # We've removed development deployment
after_deploy: echo 'Successfully executed deploy trigger for Booklist App on AWS'
env:
  global:
    secure: oea7Q5ZkzogDMbcsaXdB9tD4H8OhrVaW4fKga0h/hsl7kQKXgXbuUFNFJF0C57ik2lBFqOm73qmlnEdJrGgbWe1PiiJ96a9ncLFsObiZA5QaZLInsHCu8bRSCLMRhDPfA7Wv7LwQX5vBilDhYqyc/ySba7p3Cb8AsbOtiGhhm/LhcGQ/VWI2gfqGmALd2vs5+w3n/Pp6l4ri9mAteReAMAiT2FDlZAUN1cAnvUbS87G5In8kNb5qiQvjAuzoXbQahYsG9q5xwXKL6ncouoY6lUlFhJB+fmTYSSoJf7p+zQQCkzMfFSybaDVXAJLkApuBA93/k2X4IkE3GHeE53nQUCSXtEWBhPcN1BjDbGFgkOVepJarn6tYGS4vygRs6HQwq/sGefDT6yPAUe4k2vvfRekTilL2nQYDRVKoNhG+xCvcjQujjGqM0y4ZDlL1Ay9Vyi+H63wKebyzyAGDjXqTmfsNGzqYoNHhKZJ+dHposHgYaDcz0SkT8Rgp2nYyYRrBRRVXCxVh60BvW8yZZNqtubIYzq7XK0ZxBt4JMChnKzS3+UerEKdcpgtIX+ZqYQ2WbQ3vjG9FGDY+DI7wL75CXuXYSwKcLvGq2vCU9HsfaAgbOclIRcLR49CwjZmIAte8LYRnC0jV30duaX+dFjAEhD/XvPlG4KQmDfAH5gEfsFQ=
